ioe {
	ktor {
		host = "127.0.0.1"
		port = 8000
	}

	mongo {
		url = "mongodb://127.0.0.1:27017"
	}

	logging {
		level = "INFO"
	}

	pubsub {

	}
}

store {
	database = "business_event_management"
}
