[versions]
kotlin = "2.4.0"
serialization = "1.11.0"
coroutines = "1.11.0"
datetime = "0.8.0"
ktor = "3.5.0"
logback = "1.5.38"
compose = "1.11.1"
xmlutil = "1.0.1"
b3 = "0.1.0-SNAPSHOT"

[libraries]
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-serialization-protobuf = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf", version.ref = "serialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }

ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-darwin = { group = "io.ktor", name = "ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }

logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

pdvrieze-xmlutil = { group = "io.github.pdvrieze.xmlutil", name = "serialization", version.ref = "xmlutil" }

foundation-runtime = { group = "org.bluebikebase.foundation", name = "runtime", version.ref = "b3" }
foundation-ioe-http = { group = "org.bluebikebase.foundation", name = "io-engine-http", version.ref = "b3" }
foundation-ioe-ktor-client = { group = "org.bluebikebase.foundation", name = "io-engine-ktor-client", version.ref = "b3" }
foundation-ioe-ktor-server = { group = "org.bluebikebase.foundation", name = "io-engine-ktor-server", version.ref = "b3" }
foundation-ioe-mongo = { group = "org.bluebikebase.foundation", name = "io-engine-mongo", version.ref = "b3" }
foundation-ioe-pubsub = { group = "org.bluebikebase.foundation", name = "io-engine-pubsub", version.ref = "b3" }
foundation-ioe-udp = { group = "org.bluebikebase.foundation", name = "io-engine-udp", version.ref = "b3" }
foundation-ioe-config = { group = "org.bluebikebase.foundation", name = "io-engine-config", version.ref = "b3" }
foundation-ioe-logging = { group = "org.bluebikebase.foundation", name = "io-engine-logging", version.ref = "b3" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-plugin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
